### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [kyumikek/voxel-game#4]
l are opening up to suggestions for a new name. l feel the Voxel has to do to reach it's full potential. As a result, we are committed to this rebrand. New name candidates should not be taken by anything active, and we'd have to be careful with previous usage. Please verify this before putting a candidate forward. The criteria we are looking for is as follows:

* short
* interesting
* easy to (not mis)type

---
Kubli , KUBLI is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is a cube/regular polyhedron/polygon of dimensions ](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=kubli&bangu=en&versio=masno)

canpa , CANPA is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is a shovel/spade [bladed digging implement] for digging](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=canpa&bangu=en&versio=masno)

kunra , KUNRA is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [is/contains/is made from a mineral/ore of type/metal mined from location/lode/mine](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=kunra&bangu=en&versio=masno)

Calsle , CALSLE is mainly inspired by the [Lojban](https://en.wikipedia.org/wiki/Lojban) language word [meaning is a voxel of model/object](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=calsle&bangu=en&versio=masno)

Cltoq , CLTOQ is mainly inspired by the [Toaq](https://toaq.net/) language word [ is a cube.](https://toadua.uakci.pl/#cube)

OdinVoxel , ODINVOXEL is mainly inspired by the [Odin programming language](https://github.com/odin-lang/Odin)

**Comment by kyumikek** [comment]
Generally the name is voxeloza inspired by pixeloza an effect where you see in pixels but because it's 3d there come voxels. Tho I am unsure about the name and will be considering whether to change it

**Comment by Zig-Rust-Odin** [comment]
Creating a Group 
Matrix
Discord and https://rvlt.gg

**Comment by kyumikek** [comment]
Will do it today in the afternoon
